name: doorstop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cache-pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('scripts/requirements.txt') }}

      - name: install-pip
        run: |
            pip install -r scripts/requirements.txt

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.1.2

      - name: check-format
        run: |
          result=
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            result=$(./scripts/check-format.py $file)
            if [ result ]
            then
              echo $result
            fi
          done

      # Checks spelling, grammar and punctuation (one sentence, ended by period, etc.)
      # - name: check-spelling-grammar-punctuation
      #   run: |
      #     # WIP; not sure if Zephyr Project would need to license LanguageTool use
      #     # https://languagetool.org/
      #     # https://github.com/jxmorris12/language_tool_python
